[platformio]
name = "gRPC with PlatformIO"
description = "Show how to compile a PlatformIO project against a globally installed gRPC library."
extra_configs = private_config.ini

[env:native]
platform = native
extra_scripts = 
    pre:gen_proto.py
