[platformio]
name = "gRPC with PlatformIO"
description = "Show how to compile a PlatformIO project against a globally installed gRPC library."
extra_configs = private_config.ini

[env:native]
platform = native
build_flags = 
    -lz
    -lssl
    -lcrypto
    -lsystemd
extra_scripts = 
    pre:gen_grpc.py
